services:
  academia-db:
    image: postgres:latest
    container_name: academia-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=academia-db

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s       # Tenta a cada 10 segundos
      timeout: 5s
      retries: 10         # Aumentamos as tentativas para 10
      start_period: 90s   # <-- A GRANDE MUDANÃ‡A

  api-spring:
    container_name: api-aula
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://academia-db:5432/academia-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      academia-db:
        condition: service_healthy

volumes:
  postgres-data-local: